name: 674_final
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aiodns=3.5.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.2
  - aiosignal=1.4.0
  - arrow-cpp=21.0.0
  - attrs=25.4.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.4
  - aws-c-io=0.21.4
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.7
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.34.0
  - aws-sdk-cpp=1.11.638
  - blas=1.0
  - bottleneck=1.4.2
  - brotlicffi=1.1.0.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.4
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - datasets=3.3.2
  - dill=0.3.8
  - expat=2.7.3
  - filelock=3.20.0
  - frozenlist=1.8.0
  - fsspec=2024.12.0
  - gettext=0.21.0
  - gflags=2.2.2
  - glog=0.5.0
  - hf-xet=1.1.8
  - huggingface_hub=0.34.4
  - icu=73.1
  - idna=3.11
  - intel-openmp=2025.0.0
  - jansson=2.14
  - ld_impl_linux-64=2.44
  - libabseil=20250127.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.16.0
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libgrpc=1.71.0
  - libiconv=1.16
  - libidn2=2.3.8
  - libnghttp2=1.67.1
  - libnsl=2.0.0
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libthrift=0.22.0
  - libunistring=1.3
  - libuuid=1.41.5
  - libuv=1.48.0
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - multidict=6.7.0
  - multiprocess=0.70.15
  - ncurses=6.5
  - numexpr=2.14.1
  - numpy=2.3.5
  - numpy-base=2.3.5
  - openssl=3.0.18
  - orc=2.2.0
  - packaging=25.0
  - pandas=2.3.3
  - pip=25.3
  - propcache=0.3.1
  - pthread-stubs=0.3
  - pyarrow=21.0.0
  - pycares=4.10.0
  - pycparser=2.23
  - pysocks=1.7.1
  - python=3.12.12
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - pytz=2025.2
  - pyyaml=6.0.3
  - re2=2024.07.02
  - readline=8.3
  - regex=2025.9.1
  - requests=2.32.5
  - s2n=1.5.14
  - safetensors=0.6.2
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.1
  - sqlite=3.51.0
  - tbb=2022.0.0
  - tbb-devel=2022.0.0
  - tk=8.6.15
  - tokenizers=0.22.1
  - tqdm=4.67.1
  - transformers=4.57.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.5.0
  - utf8proc=2.6.1
  - uvloop=0.22.1
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xxhash=0.8.0
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.22.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
    - accelerate==1.12.0
    - communities==3.0.0
    - contourpy==1.3.3
    - cycler==0.12.1
    - fonttools==4.60.1
    - igraph==1.0.0
    - jinja2==3.1.6
    - kiwisolver==1.4.9
    - markupsafe==3.0.3
    - matplotlib==3.10.7
    - mpmath==1.3.0
    - networkx==3.6
    - nvidia-cublas-cu12==12.8.4.1
    - nvidia-cuda-cupti-cu12==12.8.90
    - nvidia-cuda-nvrtc-cu12==12.8.93
    - nvidia-cuda-runtime-cu12==12.8.90
    - nvidia-cudnn-cu12==9.10.2.21
    - nvidia-cufft-cu12==11.3.3.83
    - nvidia-cufile-cu12==1.13.1.3
    - nvidia-curand-cu12==10.3.9.90
    - nvidia-cusolver-cu12==11.7.3.90
    - nvidia-cusparse-cu12==12.5.8.93
    - nvidia-cusparselt-cu12==0.7.1
    - nvidia-nccl-cu12==2.27.5
    - nvidia-nvjitlink-cu12==12.8.93
    - nvidia-nvshmem-cu12==3.3.20
    - nvidia-nvtx-cu12==12.8.90
    - pillow==12.0.0
    - psutil==7.1.3
    - pyparsing==3.2.5
    - python-louvain==0.16
    - scipy==1.16.3
    - seaborn==0.13.2
    - sympy==1.14.0
    - texttable==1.7.0
    - torch==2.9.1
    - torchvision==0.24.1
    - triton==3.5.1
prefix: /home/yumo/.conda/envs/674_final
